### ISSUE TITLE
Not getting all episodes of show

### ISSUE THREAD

**Issue by Evoley** [anidl/multi-downloader-nx#324] opened 2022-06-21 15:07 UTC
### Program version

3.0.6

### Operating System

Linux

### Type

Cli

### Service

Crunchyroll

### Command used

./aniDL --service crunchy --username cm --password z --srz GYZJ43JMR --e 1 --dubLang jpn eng --dlsubs ja en -q 0 --fileName '${showTitle} - S${season} E${episode} ${title}'

### Show ID

GYZJ43JMR

### Episode

1

### Console Output

=== Multi Downloader NX 3.0.6 ===

[INFO] USER: P
[INFO] Your Country: US

[Z:GYZJ43JMR] That Time I Got Reincarnated as a Slime (Seasons: 20, EPs: 336) [DUB]
  [S:GR09CX9XN] That Time I Got Reincarnated as a Slime (English Dub) (Season: 1) [DUB]
  [S:GYE5CQ8QW] That Time I Got Reincarnated as a Slime Season 2 (English Dub) (Season: 1) [DUB]
  [S:GR49C7M7P] That Time I Got Reincarnated as a Slime OAD (English Dub) (Season: 1) [DUB]
  [S:GR75CD53N] That Time I Got Reincarnated as a Slime (Spanish Dub) (Season: 1) [DUB]
  [S:GYE5CQPW0] That Time I Got Reincarnated as a Slime (Portuguese Dub) (Season: 1) [DUB]
  [S:G6QWV0JG6] That Time I Got Reincarnated as a Slime (German Dub) (Season: 1) [DUB]
  [S:GR09CX3MM] That Time I Got Reincarnated as a Slime (French Dub) (Season: 1) [DUB]
  [S:GYDKV0K36] That Time I Got Reincarnated as a Slime (Season: 1) [SUB]
    - Availability notes: Rimuru’s adventures continue in the That Time I Got Reincarnated as a Slime manga! Read the manga that inspired the hit anime, out now from Kodansha Comics!

Can’t get enough of the show? Check out the That Time I Got Reincarnated as a Slime light novels today!
  [S:G63VC27V1] That Time I Got Reincarnated as a Slime Season 2 (Spanish Dub) (Season: 2) [DUB]
  [S:GR2PCV5NQ] That Time I Got Reincarnated as a Slime Season 2 (Portuguese Dub) (Season: 2) [DUB]
  [S:G6P8CX08P] That Time I Got Reincarnated as a Slime Season 2 (German Dub) (Season: 2) [DUB]
  [S:GY8VCP270] That Time I Got Reincarnated as a Slime Season 2 (French Dub) (Season: 2) [DUB]
  [S:G609CXQQ3] That Time I Got Reincarnated as a Slime Season 2 (Season: 2) [SUB]
  [S:G6NQCJZNG] That Time I Got Reincarnated as a Slime OAD (Spanish Dub) (Season: 6) [DUB]
  [S:GRMGC3ZE7] That Time I Got Reincarnated as a Slime OAD (Portuguese Dub) (Season: 10) [DUB]
  [S:GY25K527Y] That Time I Got Reincarnated as a Slime OAD (German Dub) (Season: 14) [DUB]
  [S:GRK5CNZG5] That Time I Got Reincarnated as a Slime OAD (French Dub) (Season: 17) [DUB]
  [S:GR8D0NQ7R] That Time I Got Reincarnated as a Slime OAD (Season: 23) [SUB]
[INFO] USER: P
[INFO] Your Country: US

[E1] That Time I Got Reincarnated as a Slime - Season 1 - Hey! Butts! [☆ English, ☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E2] That Time I Got Reincarnated as a Slime - Season 1 - The Tragedy of M? [☆ English, ☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E3] That Time I Got Reincarnated as a Slime - Season 1 - Rimuru's Glamorous Life as a Teacher, Part 1 [☆ English, ☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E4] That Time I Got Reincarnated as a Slime - Season 1 - Rimuru's Glamorous Life as a Teacher, Part 2 [☆ English, ☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E5] That Time I Got Reincarnated as a Slime - Season 1 - Extra: Rimuru's Glamorous Life as a Teacher, Part 3 [☆ English, ☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E6] That Time I Got Reincarnated as a Slime - Season 1 - Shizu [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E7] That Time I Got Reincarnated as a Slime - Season 1 - Conqueror of Flames [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E8] That Time I Got Reincarnated as a Slime - Season 1 - Inherited Will [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E9] That Time I Got Reincarnated as a Slime - Season 1 - Attack of the Ogres [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E10] That Time I Got Reincarnated as a Slime - Season 1 - The Orc Lord [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E11] That Time I Got Reincarnated as a Slime - Season 1 - Gabiru Is Here! [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E12] That Time I Got Reincarnated as a Slime - Season 1 - The Gears Spin Out of Control [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E13] That Time I Got Reincarnated as a Slime - Season 1 - The Great Clash [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E14] That Time I Got Reincarnated as a Slime - Season 1 - The One Who Devours All [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E15] That Time I Got Reincarnated as a Slime - Season 1 - The Jura Forest Alliance [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E16] That Time I Got Reincarnated as a Slime - Season 1 - Demon Lord Milim Attacks [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E17] That Time I Got Reincarnated as a Slime - Season 1 - The Gathering [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E18] That Time I Got Reincarnated as a Slime - Season 1 - Evil Creeps Closer [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E19] That Time I Got Reincarnated as a Slime - Season 1 - Charybdis [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E20] That Time I Got Reincarnated as a Slime - Season 1 - Yuuki Kagurazaka [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E21] That Time I Got Reincarnated as a Slime - Season 1 - Shizu-san's Students [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E22] That Time I Got Reincarnated as a Slime - Season 1 - Conquering the Labyrinth [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E23] That Time I Got Reincarnated as a Slime - Season 1 - Saved Souls [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E24] That Time I Got Reincarnated as a Slime - Season 1 - Black and the Mask [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[S1] That Time I Got Reincarnated as a Slime - Season 1 - Veldora's Journal [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[S2] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Digression: Hinata Sakaguchi [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E25] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Rimuru's Busy Life [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E26] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Trade with the Animal Kingdom [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E27] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Paradise, Once More [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E28] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - The Scheming Kingdom of Falmuth [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E29] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Prelude to the Disaster [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E30] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - The Beauty Makes Her Move [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E31] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Despair [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E32] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Hope [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E33] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Putting Everything on the Line [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E34] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Megiddo [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E35] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Birth of a Demon Lord [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E36] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - The One Unleashed [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[S3] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Tales: Veldora's Journal 2 [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E37] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - The Visitors [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E38] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - A Meeting of Humans and Monsters [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E39] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Ramiris's Warning [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E40] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - The Congress Dances [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E41] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - The Eve of Battle [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E42] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - The Demon Lords [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E43] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - The Signal to Begin the Banquet [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E44] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - On This Land Where It All Happened [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E45] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Adalmann, the Index Finger [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E46] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Demon Lords' Banquet ~Walpurgis~ [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E47] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Returning from the Brink [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese]
[E48] That Time I Got Reincarnated as a Slime Season 2 - Season 2 - Octagram [☆ Spanish, ☆ Portuguese, ☆ German, ☆ French, Japanese][E49] That Time I Got Reincarnated as a Slime OAD - Season 6 - Hey! Butts! [☆ Spanish]
[E50] That Time I Got Reincarnated as a Slime OAD - Season 6 - The Tragedy of M? [☆ Spanish]
[E51] That Time I Got Reincarnated as a Slime OAD - Season 6 - Rimuru's Glamorous Life as a Teacher, Part 1 [☆ Spanish]
[E52] That Time I Got Reincarnated as a Slime OAD - Season 6 - Rimuru's Glamorous Life as a Teacher, Part 2 [☆ Spanish]
[E53] That Time I Got Reincarnated as a Slime OAD - Season 6 - Extra: Rimuru's Glamorous Life as a Teacher, Part 3 [☆ Spanish]
[E54] That Time I Got Reincarnated as a Slime OAD - Season 10 - Hey! Butts! [☆ Portuguese]
[E55] That Time I Got Reincarnated as a Slime OAD - Season 10 - The Tragedy of M? [☆ Portuguese]
[E56] That Time I Got Reincarnated as a Slime OAD - Season 10 - Rimuru's Glamorous Life as a Teacher, Part 1 [☆ Portuguese]
[E57] That Time I Got Reincarnated as a Slime OAD - Season 10 - Rimuru's Glamorous Life as a Teacher, Part 2 [☆ Portuguese]
[E58] That Time I Got Reincarnated as a Slime OAD - Season 10 - Extra: Rimuru's Glamorous Life as a Teacher, Part 3 [☆ Portuguese]
[E59] That Time I Got Reincarnated as a Slime OAD - Season 14 - Hey! Butts! [☆ German]
[E60] That Time I Got Reincarnated as a Slime OAD - Season 14 - The Tragedy of M? [☆ German]
[E61] That Time I Got Reincarnated as a Slime OAD - Season 14 - Rimuru's Glamorous Life as a Teacher, Part 1 [☆ German]
[E62] That Time I Got Reincarnated as a Slime OAD - Season 14 - Rimuru's Glamorous Life as a Teacher, Part 2 [☆ German]
[E63] That Time I Got Reincarnated as a Slime OAD - Season 14 - Extra: Rimuru's Glamorous Life as a Teacher, Part 3 [☆ German]
[E64] That Time I Got Reincarnated as a Slime OAD - Season 17 - Hey! Butts! [☆ French]
[E65] That Time I Got Reincarnated as a Slime OAD - Season 17 - The Tragedy of M? [☆ French]
[E66] That Time I Got Reincarnated as a Slime OAD - Season 17 - Rimuru's Glamorous Life as a Teacher, Part 1 [☆ French]
[E67] That Time I Got Reincarnated as a Slime OAD - Season 17 - Rimuru's Glamorous Life as a Teacher, Part 2 [☆ French]
[E68] That Time I Got Reincarnated as a Slime OAD - Season 17 - Extra: Rimuru's Glamorous Life as a Teacher, Part 3 [☆ French]
[E69] That Time I Got Reincarnated as a Slime OAD - Season 23 - Hey! Butts! [Japanese]
[E70] That Time I Got Reincarnated as a Slime OAD - Season 23 - The Tragedy of M? [Japanese]
[E71] That Time I Got Reincarnated as a Slime OAD - Season 23 - Rimuru's Glamorous Life as a Teacher, Part 1 [Japanese]
[E72] That Time I Got Reincarnated as a Slime OAD - Season 23 - Rimuru's Glamorous Life as a Teacher, Part 2 [Japanese]
[E73] That Time I Got Reincarnated as a Slime OAD - Season 23 - Extra: Rimuru's Glamorous Life as a Teacher, Part 3 [Japanese]

------------------------------

[S1E1] - Hey! Butts! [✓ English, ✓ Japanese]
[INFO] Requesting: [GWDU8GV0X] That Time I Got Reincarnated as a Slime - 1 - Hey! Butts!
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/eng/- )
[INFO] Full stream found! ( 2: download_hls/eng/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/eng/- )
[INFO] Downloading video...
[INFO] Playlists URL: https://pl.crunchyroll.coId=APKAJMWSQ5S7ZB3MF5VA (adaptive_hls/eng/-)

### Additional Information

```Text
Also tested on 3.0.7 and Windows gui 3.0.7
```

**Comment by shinji257** [comment] 2022-07-01 16:43
I picked up on this in #335.  I thought it was the same but I don't see you using `--all` so I'm confused on what the issue is.  Your log shows that you only had it get episode 1 and it did that for the first season listed for each language as that is what it sees as episode 1 for the chosen dub languages.

**Comment by Evoley** [comment] 2022-07-01 17:01
The issue it seems is that it doesn't seem to find or at the very least pick up the first 5 episodes ( The Storm Dragon, Meeting the Goblins, Battle at the Goblin Village, In the Kingdom of the Dwarves and Hero King, Gazel Dwargo). It could be that the first 5 are only available in ENG only like how Funimation is.

**Comment by shinji257** [comment] 2022-07-01 17:52
There seems to be an issue with the way it is listing episodes from this command.  However, if you have it just show an individual season it seems to work fine and show all related episodes.  I actually think it is getting really confused because the first 5 episodes listed are actually from the OAD seasons.  Note that only the English OAD has a Season 1 indicator.  All the other languages (including Japanese) got their own unique Season number.  English Season 2 also got a Season 1 indicator.  Please be aware this is not an issue with multi-downloader-nx.  This is a metadata issue on CrunchRoll's end.  They have this issue all over the place.  To the point that I use `--srz` to get season ids then use `--s` to download seasons that way.  This also reveals the S## episodes that can actually overwrite the previously downloaded episode (see the report I referred to before) so you can now preemptively add an episode range or use ``--but`` and exclude the episode ID(s).  If you still want it, you can then download it separately and either change the filename format or do an override.

```
shinji@overlord:~/multi-downloader-nx$ ./aniDL --s GR09CX9XN

=== Multi Downloader NX 3.0.7 ===

[INFO] USER: [removed]
[INFO] Your Country: US

[S:GR09CX9XN] That Time I Got Reincarnated as a Slime (English Dub) (Season: 1) [DUB]
  [01|E:G31UXQKKG] ☆ 1 - The Storm Dragon, Veldora [23m52s, DUB, STREAM]
  [02|E:GPWUKENNG] ☆ 2 - Meeting the Goblins [23m52s, DUB, STREAM]
  [03|E:G2XU0JXXD] ☆ 3 - Battle at the Goblin Village [23m52s, DUB, STREAM]
  [04|E:G8WUNE33G] ☆ 4 - In the Kingdom of the Dwarves [23m52s, DUB, STREAM]
  [05|E:GZ7UVJQQE] ☆ 5 - Hero King, Gazel Dwargo [23m52s, DUB, STREAM]
  [06|E:GD9UVD99M] ☆ 6 - Shizu [23m52s, DUB, STREAM]
  [07|E:G50UZWKNN] ☆ 7 - Conqueror of Flames [23m52s, DUB, STREAM]
  [08|E:GG1U20W52] ☆ 8 - Inherited Will [23m52s, DUB, STREAM]
  [09|E:G0DUN4GWM] ☆ 9 - Attack of the Ogres [23m52s, DUB, STREAM]
  [10|E:GEVUZKJ30] ☆ 10 - The Orc Lord [23m52s, DUB, STREAM]
  [11|E:GX9UQ91MN] ☆ 11 - Gabiru Is Here! [23m52s, DUB, STREAM]
  [12|E:G4VUQZK03] ☆ 12 - The Gears Spin Out of Control [23m52s, DUB, STREAM]
  [13|E:G14U42QJX] ☆ 13 - The Great Clash [23m52s, DUB, STREAM]
  [14|E:GN7UDGXKG] ☆ 14 - The One Who Devours All [23m52s, DUB, STREAM]
  [15|E:GVWU0JNXE] ☆ 15 - The Jura Forest Alliance [23m52s, DUB, STREAM]
  [16|E:G31UXQKEG] ☆ 16 - Demon Lord Milim Attacks [23m52s, DUB, STREAM]
  [17|E:G2XU0JX1D] ☆ 17 - The Gathering [23m52s, DUB, STREAM]
  [18|E:GZ7UVJQ3E] ☆ 18 - Evil Creeps Closer [23m52s, DUB, STREAM]
  [19|E:GQJUG7NZN] ☆ 19 - Charybdis [23m52s, DUB, STREAM]
  [20|E:GWDU8GV33] ☆ 20 - Yuuki Kagurazaka [23m52s, DUB, STREAM]
  [21|E:G0DUN4GXM] ☆ 21 - Shizu-san's Students [23m52s, DUB, STREAM]
  [22|E:GEVUZKJQ0] ☆ 22 - Conquering the Labyrinth [23m52s, DUB, STREAM]
  [23|E:G9DUE7Z2K] ☆ 23 - Saved Souls [23m52s, DUB, STREAM]
  [24|E:G4VUQZK73] ☆ 24 - Black and the Mask [24m02s, DUB, STREAM]
  [S01|E:GMKUXW900] ☆ 24.5 - Veldora's Journal [23m56s, DUB, STREAM]

[INFO] Episodes not selected!
  ```
  shinji@overlord:~/multi-downloader-nx$ ./aniDL --s GYDKV0K36

=== Multi Downloader NX 3.0.7 ===

[INFO] USER: [removed]
[INFO] Your Country: US

[S:GYDKV0K36] That Time I Got Reincarnated as a Slime (Season: 1) [SUB]
  - Availability notes: Rimuru’s adventures continue in the That Time I Got Reincarnated as a Slime manga! Read the manga that inspired the hit anime, out now from Kodansha Comics!

Can’t get enough of the show? Check out the That Time I Got Reincarnated as a Slime light novels today!
  [01|E:GRQW9GW7R] 1 - The Storm Dragon, Veldora [23m42s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [02|E:G6245P09Y] 2 - Meeting the Goblins [23m42s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [03|E:G679131ZY] 3 - Battle at the Goblin Village [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [04|E:GYVDMVJWY] 4 - In the Kingdom of the Dwarves [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [05|E:G6P5D7PK6] 5 - Hero King, Gazel Dwargo [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [06|E:GRDKDK2WY] 6 - Shizu [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [07|E:G6DKDDG4R] 7 - Conqueror of Flames [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [08|E:GY8DXM4GY] 8 - Inherited Will [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [09|E:GR1X5QW1R] 9 - Attack of the Ogres [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [10|E:GYJ02JW56] 10 - The Orc Lord [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [11|E:GY0X33146] 11 - Gabiru Is Here! [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [12|E:GYZJW058R] 12 - The Gears Spin Out of Control [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [13|E:GR242MN56] 13 - The Great Clash [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [14|E:G69VZ5N8Y] 14 - The One Who Devours All [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [15|E:GR0X23W7Y] 15 - The Jura Forest Alliance [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [16|E:GR1XZ8PGR] 16 - Demon Lord Milim Attacks [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [17|E:G6VD747Q6] 17 - The Gathering [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [18|E:GRQW5X2GR] 18 - Evil Creeps Closer [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [19|E:G69V92MWY] 19 - Charybdis [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [20|E:G60XZ404R] 20 - Yuuki Kagurazaka [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [21|E:GR24Q8K76] 21 - Shizu-san's Students [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [22|E:GRJ04G50Y] 22 - Conquering the Labyrinth [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [23|E:GREX4EV3Y] 23 - Saved Souls [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [24|E:G6ME5KQWR] 24 - Black and the Mask [23m50s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru
  [S01|E:GY4PXGN16] 24.5 - Veldora's Journal [23m44s, SUB, STREAM]
    - Subtitles: en, es-419, es, pt, fr, de, ar, it, ru

[INFO] Episodes not selected!
  ```

**Comment by izu-co** [comment] 2022-07-01 18:30
I got some free time in the near future and will take a look at it, but here a quick few words:

- I know that Crunchyroll has a lot of metadata issues (like dubbed season one's being season two, …)
- `--srz` is my attempt at fixing the metadata issue (though comparing episode and season names for example, tho the logic is more complex). Therefore, it will never work in all cases.
- It can very well be that your issue is not resolvable for me, because of the metadata issues. If so, please download the episodes individually and merge them by hand.
- I am grateful for every reported issue, so don't think I am mad or anything, just wanted to give you a heads-up

**Comment by izu-co** [comment] 2022-07-02 12:08
I just looked at it and concluded that there is no easy fix for this. The issue is on Crunchyroll side for not setting the metadata correctly. Please use `-s` for this show.

**Closed by izu-co** 2022-07-02 12:08 UTC
Labels: bug
