### ISSUE TITLE
[BUG]: Fails to download the last piece of data.

### ISSUE THREAD

**Issue by Kapppa** [anidl/multi-downloader-nx#492] opened 2023-07-06 23:17 UTC
### Program version

4.0.3

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

aniDL --service crunchy --srz GJ0H7Q87Z -e 2-13

### Show ID

GJ0H7Q87Z 

### Episode

2-13

### Console Output

```Shell
[ERROR] Part 356 download error:
        Response code 404 (Not Found)
[ERROR] 1 parts not downloaded
[ERROR] DL Stats: {"first":1,"total":356,"completed":350}
```

### Additional Information

Fails to download the last piece of data. Happens on all qualities, E01 was fine, its only the episodes after.

**Comment by AnimeDL** [comment] 2023-07-06 23:25
Oh that's very weird, I can confirm the same behavior. I suspect it's an issue with crunchyroll, and the downloaded video plays fine up until the last part. You can however download another stream of it using `--kstream 4` and it appears to download fine.

**Comment by AnimeDL** [comment] 2023-07-09 01:22
I'm going to close this since I believe it to be a crunchyroll issue, and there are workarounds. Feel free to re-open if needed

**Closed by AnimeDL** 2023-07-09 01:22 UTC
Labels: bug
