### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dobby321** [anidl/multi-downloader-nx#416] opened 2022-11-11 22:05 UTC
### Program version

3.1.0

### Operating System

Windows

### Type

Cli

### Service

Irrelevant

### Command used

anidl.exe --service crunchy --s GRZXCMJKG -q 4 --nosubs --dubLang eng --mkv -e 1

### Show ID

GRZXCMJKG

### Episode

1

### Console Output

[INFO] Subtitles: en (Total: 1)
[INFO] Required fonts: Trebuchet MS (Total: 1)
[WARN] MKVMerge not found, skip muxing...

[INFO] Done!

### Additional Information

```Text
the problem is mkvMerge not found and i have looked at previous issues threads and the information there does not work
```

**Comment by XxUnkn0wnxX** [comment] 2023-01-14 19:05
not a bug, you simply do not have mkvmerge in your PATH
I'm not sure how this is done on windows though..

or you can download mkvtoolnix setup here: https://www.fosshub.com/MKVToolNix.html
then install it, then navigate to program files where mkvtoolnix is installed & copy over "mkvmerge.exe" from there to the root dir of where you have your anidl.exe binary file.

or edit the "bin-path.yml" & specify the full path to the "mkvmerge.exe" binary file.

**Comment by AnimeDL** [comment] 2023-07-10 15:56
Closing because it should be resolved.

**Closed by AnimeDL** 2023-07-10 15:56 UTC
Labels: bug
