### ISSUE TITLE
[BUG]: Crunchyroll download error

### ISSUE THREAD

**Issue by DekuQJ03** [anidl/multi-downloader-nx#572] opened 2023-12-15 00:51 UTC
### Program version

4.3.2

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

node index.js --service crunchy -s GRZXCMKM3 -q 0 --hslang es-419 -e 12 --mkv

### Show ID

GRZXCMKM3

### Episode

12

### Console Output

```Shell
[S:GRZXCMKM3] My Daughter Left the Nest and Returned an S-Rank Adventurer (Season: 1) [SIMULCAST, SUB]
  - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [01|E:G4VUQ1XJK] 1 - The Melancholy of Angeline [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [02|E:G14U49E0J] 2 - Belgrieve the Red Ogre [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [03|E:GJWU29XG1] 3 - Welcome Home, Angeline [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [04|E:GN7UD279D] ☆ 4 - Quiet Days in Turnera with the Occasional Family Spat [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [05|E:GK9U3M40G] ☆ 5 - The Road to Bordeaux [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [06|E:G50UZX49G] ☆ 6 - Rebels Acting in Secret [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [07|E:GWDU8EKWZ] ☆ 7 - A Long Night and a Bright Dawn [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [08|E:GG1U24EQK] ☆ 8 - Meeting the Inhabitants of the Woods [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [09|E:G0DUND01Q] ☆ 9 - Father and Daughter Meet New People [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [10|E:GEVUZXG2P] ☆ 10 - Wriggling Malice [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
  [11|E:G7PU4MVZW] ☆ 11 - Belgrieve's Decision [23m39s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru
 ✓[12|E:G9DUE5PQP] ☆ 12 - Confronting the Past [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru

Requesting: [G9DUE5PQP] My Daughter Left the Nest and Returned an S-Rank Adventurer - 12 - Confronting the Past
[ERROR] HTTPError 404: Not Found
[ERROR] Request Stream URLs FAILED! Attempting fallback
[WARN] No full streams found!
[ERROR] Unable to download selected episode 12
```

### Additional Information

I have this error since today with all the anime I want to download (old and new). My account is premium and the series is available in my region.

**Comment by kokoboko5** [comment] 2023-12-15 00:57
I have the same problem

Requesting: [G4VUQ851V] Rurouni Kenshin - 1 - Kenshin - Himura Battosai
[WARN] No full streams found!
[ERROR] Unable to download selected episode 1

**Comment by kokoboko5** [comment] 2023-12-15 00:58
> [AnidlSupport](/AnidlSupport) and [AnimeDL](/AnimeDL)

@AnimeDL @AnidlSupport

**Comment by kokoboko5** [comment] 2023-12-15 00:58
> I have the same problem
> 
> Requesting: [G4VUQ851V] Rurouni Kenshin - 1 - Kenshin - Himura Battosai [WARN] No full streams found! [ERROR] Unable to download selected episode 1

@AnimeDL @AnidlSupport

**Comment by kokoboko5** [comment] 2023-12-15 00:59
> I have the same problem
> 
> Requesting: [G4VUQ851V] Rurouni Kenshin - 1 - Kenshin - Himura Battosai [WARN] No full streams found! [ERROR] Unable to download selected episode 1

@AnimeDL @AnidlSupport @anidl-git

**Comment by Jaynator495** [comment] 2023-12-15 01:39
Working on it, unfortunately, it looks like they disabled the non DRM streams, so it looks like DRM decryption will need to be added

**Comment by pratyushpati11** [comment] 2023-12-15 05:45
> Working on it, unfortunately, it looks like they disabled the non DRM streams, so it looks like DRM decryption will need to be added

It is downloading from yt-dlp

**Comment by Jaynator495** [comment] 2023-12-15 07:05
> > Working on it, unfortunately, it looks like they disabled the non DRM streams, so it looks like DRM decryption will need to be added
> 
> It is downloading from yt-dlp using adaptive hls.

Noticed that, and I'm building a way that doesn't involve DRM decryption as a temporary measure. But it likely won't last forever, so I will still have DRM decryption high on my todo list.

**Comment by AnimeDL** [comment] 2023-12-15 17:56
Alright, created the hotfix, release 4.4.0 should now work again. A more proper fix with the DRM decryption will come at a later time. Note: --kstream 1 is 720p, and --kstream 2 is 1080p, I have changed the default, but check your cli-defaults and make sure it is also changed to reflect this change.

**Comment by Decooh** [comment] 2023-12-15 19:03
Hi.. after the update I got this new error
![image](https://github.com/anidl/multi-downloader-nx/assets/42754712/e10ad997-6ceb-48ce-b3f4-27b12d06bd7b)

**Comment by Jaynator495** [comment] 2023-12-15 19:05
Yea, the fallback still uses the other API, so it's incompatible with the code right now, does everything 404 for you, or just that episode??

**Comment by Decooh** [comment] 2023-12-15 19:17
> Yea, the fallback still uses the other API, so it's incompatible with the code right now, does everything 404 for you, or just that episode??

I tried a few episodes here and it kept giving the same error.

**Comment by pratyushpati11** [comment] 2023-12-15 19:28
For Cli only or GUI also?

**Comment by Jaynator495** [comment] 2023-12-15 19:32
> For Cli only or GUI also?

The fix should be for both GUI and CLI, if that's what you're asking

**Comment by kokoboko5** [comment] 2023-12-15 20:48
There are anime that download successfully, such as:

The Kingdoms of Ruin
Frieren: Beyond Journey's End
Girlfriend, Girlfriend Season 2
The Rising of the Shield Hero Season 3

There are also anime that I cannot download, such as:

Our Dating Story: The Experienced You and The Inexperienced Me
HYPNOSISMIC -Division Rap Battle- Rhyme Anima PLUS
Let Me Check the Walkthrough First

These are just examples of today's anime

==================

Requesting: [G0DUND50X] Our Dating Story: The Experienced You and The Inexperienced Me - 11 - Our Breakup Story: The Experienced You and the Inexperienced Me Break Up.
[ERROR] HTTPError 404: Not Found
[ERROR] Request Stream URLs FAILED! Attempting fallback
node:internal/process/task_queues:95
    runMicrotasks();
    ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Crunchy.<anonymous> (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.5.0

**Comment by DekuQJ03** [comment] 2023-12-16 01:34
the same thing happens to me, it works in some anime but not in others, I hope it will be solved soon, I will be attentive to the new version, thank you very much for your effort.

**Comment by AnimeDL** [comment] 2023-12-17 02:21
Alright, I believe the latest commit fixes it, if you're comfortable building yourself, I'd like some feedback from those that were experiencing the 404 issue if it's still happening

**Comment by AnimeDL** [comment] 2023-12-17 03:35
Someone has confirmed on our discord that the 404 issue is working with the new fallback, so I've gone ahead and released 4.4.1. Next release after this should add DRM decryption hopefully

**Comment by DekuQJ03** [comment] 2023-12-17 16:39
with version 4.4.1, so far all the anime I have tried to download has worked successfully, thank you very much.

**Comment by ArturiaPendragon** [comment] 2023-12-19 13:30
Hello, i tested it with latest version (and building myself) but i get error with this commands :

`node index.js --service crunchy -e "GG1U24009" --ksteam 2`

or 

`node index.js --service crunchy --extid EPI.911167 -x 2 --fileName file.1080p --skipSubMux --partsize 10 --skipUpdate --novids --noaudio --ksteam 2`

```
Requested object ID: GG1U24009
 ✓[S:GR3VC212W|E:GG1U24009|EPI.911167] A Playthrough of a Certain Dude's VRMMO Life - 12 - Earth Gets Angry [23m40s, SUB, STREAM]
    - Subtitles: en, es-419, es-ES, pt-BR, fr, de, ar, it, ru

Requesting: [E:GG1U24009] A Playthrough of a Certain Dude's VRMMO Life - 12 - Earth Gets Angry
[ERROR] HTTPError 404: Not Found
[ERROR] Request Stream URLs FAILED! Attempting fallback
/home/destiny/.scripts/mlt-3/lib/crunchy.js:1135
                for (const s of Object.keys(pbStreams)) {
                                       ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Crunchy.<anonymous> (/home/destiny/.scripts/mlt-3/lib/crunchy.js:1135:40)
    at Generator.next (<anonymous>)
    at fulfilled (/home/destiny/.scripts/mlt-3/lib/crunchy.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.3.0
```

**Comment by AnimeDL** [comment] 2023-12-24 19:57
Pushed a fix for -e and --extid, I don't think I'm going to create a release for this since I'm (hopefully) close to completion for the MPD & Decryption update, so you'll have to build.

**Comment by ArturiaPendragon** [comment] 2023-12-26 15:36
Works on my WSL :) Thanks :) (-e and --extid)

**Comment by AnimeDL** [comment] 2024-01-10 19:24
Alright, this is pretty thoroughly fixed now, so I'm going to go ahead and close this.

**Closed by AnimeDL** 2024-01-10 19:24 UTC
Labels: bug
