### ISSUE TITLE
FFmpeg not found

### ISSUE THREAD

**Issue by BuckMisterFullerene** [anidl/multi-downloader-nx#208] opened 2022-01-01 21:04 UTC
### Program version

2.0.14

### Service

Funimation

### Command used

aniDL.exe --service "funi" -s 34200 -e 1 -q 0 --nosubs --mp4

### Show ID

34200

### Episode

1

### Console Output

=== Multi Downloader NX 2.0.14 ===

[#34200] D.Gray-man (2006)
[0001] D.Gray-man - #01 The Boy Who Hunts Akuma (22:56) [SD480, Japanese, English] (selected)
[0002] D.Gray-man - #02 The Black Order (22:56) [SD480, English, Japanese]
[0003] D.Gray-man - #03 The Ghost of Mater (22:56) [SD480, Japanese, English]
[0004] D.Gray-man - #04 Old Man of the Soil and a Lonely Night's Aria (22:56) [SD480, Japanese, English]
[0005] D.Gray-man - #05 Let Me Hear the Lullaby (22:56) [SD480, Japanese, English]
[0006] D.Gray-man - #06 That Which Calls Forth Disaster (22:56) [SD480, English, Japanese]
[0007] D.Gray-man - #07 Tombstone of Memories (22:56) [SD480, English, Japanese]
[0008] D.Gray-man - #08 The Black Order Annihilation Incident (22:56) [SD480, English, Japanese]
[0009] D.Gray-man - #09 The Rewinding Town (22:56) [SD480, English, Japanese]
[0010] D.Gray-man - #10 The Bad Luck Woman's Innocence (22:56) [SD480, English, Japanese]
[0011] D.Gray-man - #11 Miranda Lotto's Feelings (22:56) [SD480, English, Japanese]
[0012] D.Gray-man - #12 And Snow Falls Over the Town (22:56) [SD480, Japanese, English]
[0013] D.Gray-man - #13 With the Coat (22:56) [SD540, English, Japanese]
[0014] D.Gray-man - #14 The Leaf of Revival (22:56) [SD480, Japanese, English]
[0015] D.Gray-man - #15 Beyond the Snowstorm (22:56) [SD480, Japanese, English]
[0016] D.Gray-man - #16 Millennium Swordsman (22:56) [SD480, English, Japanese]
[0017] D.Gray-man - #17 Pride of the Swordsman (22:56) [SD480, Japanese, English]
[0018] D.Gray-man - #18 Lenalee's Love (22:56) [SD480, Japanese, English]
[0019] D.Gray-man - #19 Vampire of the Solitary Castle (22:56) [SD480, Japanese, English]
[0020] D.Gray-man - #20 Go For It, Exorcists! (22:56) [SD480, Japanese, English]
[0021] D.Gray-man - #21 Krory Attacks (22:56) [SD480, Japanese, English]
[0022] D.Gray-man - #22 The Truth About Eliade (22:56) [SD480, English, Japanese]
[0023] D.Gray-man - #23 The Vampire Whom I Loved (22:56) [SD480, Japanese, English]
[0024] D.Gray-man - #24 Krory's New Beginning (22:56) [SD486, Japanese, English]
[0025] D.Gray-man - #25 The General's Chains (22:56) [SD480, Japanese, English]
[0026] D.Gray-man - #26 The Beginning of the End (22:56) [SD480, Japanese, English]
[0027] D.Gray-man S2 - #27 My Mentor, General Cross (22:56) [SD480, Japanese, English]
[0028] D.Gray-man S2 - #28 Exorcist Krory (22:56) [SD480, Japanese, English]
[0029] D.Gray-man S2 - #29 The One Who Sells Souls, Part 1 (22:56) [SD480, Japanese, English]
[0030] D.Gray-man S2 - #30 The One Who Sells Souls, Part 2 (22:56) [SD480, Japanese, English]
[0031] D.Gray-man S2 - #31 Lost Miranda (22:56) [SD480, English, Japanese]
[0032] D.Gray-man S2 - #32 Mysterious Ghost Ship (22:56) [SD480, Japanese, English]
[0033] D.Gray-man S2 - #33 The Village Where a Witch Lives, Part 1 (22:56) [SD480, Japanese, English]
[0034] D.Gray-man S2 - #34 The Village Where a Witch Lives, Part 2 (22:56) [SD480, English, Japanese]
[0035] D.Gray-man S2 - #35 Exorcist Clad in Wind (22:56) [SD480, English, Japanese]
[0036] D.Gray-man S2 - #36 Shroud of Darkness (22:56) [SD480, Japanese, English]
[0037] D.Gray-man S2 - #37 Charity Bell (22:56) [SD540, Japanese, English]
[0038] D.Gray-man S2 - #38 Froi Tiedoll (22:56) [SD480, Japanese, English]
[0039] D.Gray-man S2 - #39 Silent Coffins (22:56) [SD480, Japanese, English]
[0040] D.Gray-man S2 - #40 Requiem Rose (22:56) [SD480, Japanese, English]
[0041] D.Gray-man S2 - #41 A New Assassin (22:56) [SD480, English, Japanese]
[0042] D.Gray-man S2 - #42 The Black Cat's Traps (22:56) [SD480, Japanese, English]
[0043] D.Gray-man S2 - #43 The Wandering Stone Statue (22:56) [SD480, English, Japanese]
[0044] D.Gray-man S2 - #44 Iron Fan Maid (22:56) [SD480, English, Japanese]
[0045] D.Gray-man S2 - #45 Strange Mansion (22:56) [SD480, Japanese, English]
[0046] D.Gray-man S2 - #46 Illusions in the Snow (22:56) [SD480, Japanese, English]
[0047] D.Gray-man S2 - #47 The Crystal Girl (22:56) [SD480, Japanese, English]
[0048] D.Gray-man S2 - #48 Wavering Accommodator (22:56) [SD480, Japanese, English]
[0049] D.Gray-man S2 - #49 Lulu Bell's Bell (22:56) [SD480, Japanese, English]
[0050] D.Gray-man S2 - #50 Feelings of Devotion (22:56) [SD480, Japanese, English]
[0051] D.Gray-man S2 - #51 Set Sail, to the East (22:56) [SD480, Japanese, English]
[0052] D.Gray-man S3 - #52 Raid (23:00) [SD480, Japanese, English]
[0053] D.Gray-man S3 - #53 Fallen One (23:00) [SD480, Japanese, English]
[0054] D.Gray-man S3 - #54 The Beginning of the Night of the End (23:00) [SD480, Japanese, English]
[0055] D.Gray-man S3 - #55 A Scream (23:00) [SD480, Japanese, English]
[0056] D.Gray-man S3 - #56 Delete (23:00) [SD480, Japanese, English]
[0057] D.Gray-man S3 - #57 Loss and Reunion (23:00) [SD480, Japanese, English]
[0058] D.Gray-man S3 - #58 Asian Branch (23:00) [SD480, Japanese, English]
[0059] D.Gray-man S3 - #59 The Road of the Pledged (23:00) [SD480, Japanese, English]
[0060] D.Gray-man S3 - #60 Title (23:00) [SD480, Japanese, English]
[0061] D.Gray-man S3 - #61 Sinking Darkness (23:00) [SD480, Japanese, English]
[0062] D.Gray-man S3 - #62 Maiden Who Has Fallen into Darkness (23:00) [SD480, Japanese, English]
[0063] D.Gray-man S3 - #63 Ship Stalled, Girl Remains Absent (23:00) [SD480, Japanese, English]
[0064] D.Gray-man S3 - #64 Message (23:00) [SD480, Japanese, English]
[0065] D.Gray-man S3 - #65 Landing (23:00) [SD480, Japanese, English]
[0066] D.Gray-man S3 - #66 Confusion and Impatience (23:00) [SD480, Japanese, English]
[0067] D.Gray-man S3 - #67 Heading to Edo (23:00) [SD480, Japanese, English]
[0068] D.Gray-man S3 - #68 Silence (23:00) [SD480, Japanese, English]
[0069] D.Gray-man S3 - #69 Invasion (23:00) [SD480, Japanese, English]
[0070] D.Gray-man S3 - #70 God's Clown (23:00) [SD480, Japanese, English]
[0071] D.Gray-man S3 - #71 The Name Chronicled (23:00) [SD480, Japanese, English]
[0072] D.Gray-man S3 - #72 Showdown in the Capital (23:00) [SD480, Japanese, English]
[0073] D.Gray-man S3 - #73 Kanda Joins the Battle (23:00) [SD480, English, Japanese]
[0074] D.Gray-man S3 - #74 Edo Annihilated (23:00) [SD480, Japanese, English]
[0075] D.Gray-man S3 - #75 Clown and Auguste (23:00) [SD480, Japanese, English]
[0076] D.Gray-man S3 - #76 A Key and Noah's Doors (23:00) [SD480, Japanese, English]
[0077] D.Gray-man S3 - #77 The Skinn Bolic Room (23:00) [SD480, Japanese, English]
[0078] D.Gray-man S4 - #78 Forbidden Skill, Sangen Style (23:00) [SD480, Japanese, English]
[0079] D.Gray-man S4 - #79 Noah's Memory (23:00) [SD480, Japanese, English]
[0080] D.Gray-man S4 - #80 The Twins' Traps (23:00) [SD480, Japanese, English]
[0081] D.Gray-man S4 - #81 Debt Crisis (23:00) [SD480, Japanese, English]
[0082] D.Gray-man S4 - #82 Bad Game (23:00) [SD480, Japanese, English]
[0083] D.Gray-man S4 - #83 Jasdevi Enters the Scene (23:00) [SD480, Japanese, English]
[0084] D.Gray-man S4 - #84 Bloody Krory (23:00) [SD480, Japanese, English]
[0085] D.Gray-man S4 - #85 Dark-Colored Rhapsody (23:00) [SD480, Japanese, English]
[0086] D.Gray-man S4 - #86 Weak Humans (23:00) [SD480, Japanese, English]
[0087] D.Gray-man S4 - #87 Transcendent One (23:00) [SD480, Japanese, English]
[0088] D.Gray-man S4 - #88 Lavi (23:00) [SD480, Japanese, English]
[0089] D.Gray-man S4 - #89 Voice of Darkness (23:00) [SD480, English, Japanese]
[0090] D.Gray-man S4 - #90 Black Carnival (23:00) [SD480, Japanese, English]
[0091] D.Gray-man S4 - #91 Judgment (23:00) [SD480, Japanese, English]
[0092] D.Gray-man S4 - #92 Shadow of the Player (23:00) [SD480, Japanese, English]
[0093] D.Gray-man S4 - #93 Melody (23:00) [SD480, Japanese, English]
[0094] D.Gray-man S4 - #94 Homecoming (23:00) [SD480, Japanese, English]
[0095] D.Gray-man S4 - #95 Lamb and Dog (23:00) [SD480, Japanese, English]
[0096] D.Gray-man S4 - #96 Still the Clock Ticks (23:00) [SD480, Japanese, English]
[0097] D.Gray-man S4 - #97 Attack on Headquarters (23:00) [SD480, Japanese, English]
[0098] D.Gray-man S4 - #98 The Power of Generals (23:00) [SD480, Japanese, English]
[0099] D.Gray-man S4 - #99 The Noah of Lust (23:00) [SD480, Japanese, English]
[0100] D.Gray-man S4 - #100 Level 4 (23:00) [SD480, Japanese, English]
[0101] D.Gray-man S4 - #101 To the God I Hate So Much (23:00) [SD480, Japanese, English]
[0102] D.Gray-man S4 - #102 The Promise (23:00) [SD480, Japanese, English]
[0103] D.Gray-man S4 - #103 Echoes in the Long Morning (23:00) [SD480, Japanese, English]
[0104] D.Gray-man S5 - #104 HALLOW: The Fourteenth (24:00) [SD540, Japanese, English]
[0105] D.Gray-man S5 - #105 HALLOW: Lonely Boy (24:00) [SD540, English, Japanese]
[0106] D.Gray-man S5 - #106 HALLOW: It’ll Be Fine If I Wash My Face (24:00) [SD540, English, Japanese]
[0107] D.Gray-man S5 - #107 HALLOW: Blood Crusade (24:00) [SD540, Japanese, English]
[0108] D.Gray-man S5 - #108 HALLOW: Alma Karma (24:00) [SD540, English, Japanese]
[0109] D.Gray-man S5 - #109 HALLOW: friend (24:00) [SD540, Japanese, English]
[0110] D.Gray-man S5 - #110 HALLOW: The Truth about a Sterile Flower (24:00) [SD540, English, Japanese]
[0111] D.Gray-man S5 - #111 HALLOW: Awakening (24:00) [SD540, English, Japanese]
[0112] D.Gray-man S5 - #112 HALLOW: Little Good-Bye (24:00) [SD540, English, Japanese]
[0113] D.Gray-man S5 - #113 HALLOW: Sinner in Despair (24:00) [SD540, English, Japanese]
[0114] D.Gray-man S5 - #114 HALLOW: Hidden One (24:00) [SD540, English, Japanese]
[0115] D.Gray-man S5 - #115 HALLOW: My Home (24:00) [SD540, English, Japanese]
[0116] D.Gray-man S5 - #116 HALLOW: Walker (24:00) [SD540, English, Japanese]

[INFO] Selected Episodes: 0001

[INFO] D.Gray-man - S1E1 - The Boy Who Hunts Akuma
[INFO] Available streams (Non-Encrypted):
[#67038] English [Uncut]
[#76188] Japanese [Uncut] (selected)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 416x234 (456KiB/s)
         2: 640x360 (698KiB/s)
         3: 768x432 (1118KiB/s)
         4: 768x432 (1565KiB/s)
[INFO] Selected layer: 4 (768x432) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V1692988/c76cd67a-662c-4cb3-87af-2cbe07fc0b07strnv-hl149_streaming_video_768_432_1100000_index.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMTY5Mjk4OC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQxMDczNTU4fX19XX0_&Signature=rD6OGpoYvt5xicWdR6YS4YcVEDMP7g-iMLBCDA7iGGhuoXVxa2Mx9Iei2glhqcTtf0n-qJZxBzvum~6-8lMCF0ywO4bXkJ0XBW951vzD1y5kc2h4FNk-8IxNlQaiKQaXe6DgHGKYoZj2Qr~FyadnuGozyWQM1UYmrGxGTqnpLZcFGlErs7gXxthLKTCzAtXHsOuHYoNMFyp2xPy7kRutq300jLKKQNMEp7sw9l72yLCczOPlD32VCaWtmFPoWgHoXI76OHNXNV~mX7lXQNLVY0FSQ6vIYNE-p0Rt16xYn0O1lFsgj3yXrN3d6Twkgx6E5LpcY68M1te35NDwoMExsw__&rt=1369744
[INFO] Output filename: [Funimation] D.Gray-man - S01E01 [432p].ts
[INFO] Saving stream to «C:\Users\yveso\Downloads\multi-downloader-nx-2.0.14-win64\videos\[Funimation] D.Gray-man - S01E01 [432p].video.ts»...
[INFO] 10 of 687 parts downloaded [1%] (9m22s | 0.28Mb/s)
[INFO] 20 of 687 parts downloaded [3%] (10m14s | 0.27Mb/s)
[INFO] 30 of 687 parts downloaded [4%] (9m52s | 0.28Mb/s)
[INFO] 40 of 687 parts downloaded [6%] (10m46s | 0.24Mb/s)
[INFO] 50 of 687 parts downloaded [7%] (12m43s | 0.20Mb/s)
[INFO] 60 of 687 parts downloaded [9%] (11m10s | 0.23Mb/s)
[INFO] 70 of 687 parts downloaded [10%] (10m31s | 0.23Mb/s)
[INFO] 80 of 687 parts downloaded [12%] (9m50s | 0.25Mb/s)
[INFO] 90 of 687 parts downloaded [13%] (10m00s | 0.24Mb/s)
[INFO] 100 of 687 parts downloaded [15%] (9m28s | 0.24Mb/s)
[INFO] 110 of 687 parts downloaded [16%] (8m46s | 0.26Mb/s)
[INFO] 120 of 687 parts downloaded [17%] (8m18s | 0.26Mb/s)
[INFO] 130 of 687 parts downloaded [19%] (8m29s | 0.25Mb/s)
[INFO] 140 of 687 parts downloaded [20%] (8m06s | 0.26Mb/s)
[INFO] 150 of 687 parts downloaded [22%] (7m43s | 0.27Mb/s)
[INFO] 160 of 687 parts downloaded [23%] (7m25s | 0.27Mb/s)
[INFO] 170 of 687 parts downloaded [25%] (7m03s | 0.28Mb/s)
[INFO] 180 of 687 parts downloaded [26%] (6m44s | 0.28Mb/s)
[INFO] 190 of 687 parts downloaded [28%] (6m26s | 0.29Mb/s)
[INFO] 200 of 687 parts downloaded [29%] (6m14s | 0.29Mb/s)
[INFO] 210 of 687 parts downloaded [31%] (5m56s | 0.30Mb/s)
[INFO] 220 of 687 parts downloaded [32%] (5m40s | 0.31Mb/s)
[INFO] 230 of 687 parts downloaded [33%] (5m24s | 0.32Mb/s)
[INFO] 240 of 687 parts downloaded [35%] (5m13s | 0.32Mb/s)
[INFO] 250 of 687 parts downloaded [36%] (5m01s | 0.33Mb/s)
[INFO] 260 of 687 parts downloaded [38%] (4m51s | 0.33Mb/s)
[INFO] 270 of 687 parts downloaded [39%] (6m11s | 0.25Mb/s)
[INFO] 280 of 687 parts downloaded [41%] (5m57s | 0.26Mb/s)
[INFO] 290 of 687 parts downloaded [42%] (5m42s | 0.26Mb/s)
[INFO] 300 of 687 parts downloaded [44%] (5m27s | 0.26Mb/s)
[INFO] 310 of 687 parts downloaded [45%] (5m13s | 0.27Mb/s)
[INFO] 320 of 687 parts downloaded [47%] (5m00s | 0.27Mb/s)
[INFO] 330 of 687 parts downloaded [48%] (4m49s | 0.28Mb/s)
[INFO] 340 of 687 parts downloaded [49%] (4m36s | 0.28Mb/s)
[INFO] 350 of 687 parts downloaded [51%] (4m23s | 0.28Mb/s)
[INFO] 360 of 687 parts downloaded [52%] (4m12s | 0.29Mb/s)
[INFO] 370 of 687 parts downloaded [54%] (4m02s | 0.29Mb/s)
[INFO] 380 of 687 parts downloaded [55%] (3m57s | 0.29Mb/s)
[INFO] 390 of 687 parts downloaded [57%] (3m47s | 0.29Mb/s)
[INFO] 400 of 687 parts downloaded [58%] (3m38s | 0.29Mb/s)
[INFO] 410 of 687 parts downloaded [60%] (3m29s | 0.29Mb/s)
[INFO] 420 of 687 parts downloaded [61%] (3m19s | 0.30Mb/s)
[INFO] 430 of 687 parts downloaded [63%] (3m09s | 0.30Mb/s)
[INFO] 440 of 687 parts downloaded [64%] (2m59s | 0.30Mb/s)
[INFO] 450 of 687 parts downloaded [66%] (2m51s | 0.31Mb/s)
[INFO] 460 of 687 parts downloaded [67%] (2m46s | 0.30Mb/s)
[INFO] 470 of 687 parts downloaded [68%] (2m38s | 0.30Mb/s)
[INFO] 480 of 687 parts downloaded [70%] (2m35s | 0.29Mb/s)
[INFO] 490 of 687 parts downloaded [71%] (2m26s | 0.30Mb/s)
[INFO] 500 of 687 parts downloaded [73%] (2m18s | 0.30Mb/s)
[INFO] 510 of 687 parts downloaded [74%] (2m09s | 0.30Mb/s)
[INFO] 520 of 687 parts downloaded [76%] (2m02s | 0.30Mb/s)
[INFO] 530 of 687 parts downloaded [77%] (1m55s | 0.30Mb/s)
[INFO] 540 of 687 parts downloaded [79%] (1m48s | 0.30Mb/s)
[INFO] 550 of 687 parts downloaded [80%] (1m40s | 0.30Mb/s)
[INFO] 560 of 687 parts downloaded [82%] (1m32s | 0.30Mb/s)
[INFO] 570 of 687 parts downloaded [83%] (1m26s | 0.30Mb/s)
[INFO] 580 of 687 parts downloaded [84%] (1m18s | 0.30Mb/s)
[INFO] 590 of 687 parts downloaded [86%] (1m11s | 0.30Mb/s)
[INFO] 600 of 687 parts downloaded [87%] (1m03s | 0.31Mb/s)
[INFO] 610 of 687 parts downloaded [89%] (55s | 0.31Mb/s)
[INFO] 620 of 687 parts downloaded [90%] (48s | 0.31Mb/s)
[INFO] 630 of 687 parts downloaded [92%] (40s | 0.31Mb/s)
[INFO] 640 of 687 parts downloaded [93%] (33s | 0.31Mb/s)
[INFO] 650 of 687 parts downloaded [95%] (26s | 0.32Mb/s)
[INFO] 660 of 687 parts downloaded [96%] (19s | 0.32Mb/s)
[INFO] 670 of 687 parts downloaded [98%] (12s | 0.32Mb/s)
[INFO] 680 of 687 parts downloaded [99%] (5s | 0.32Mb/s)
[INFO] 687 of 687 parts downloaded [100%] (0s | 0.32Mb/s)
[INFO] Saving stream to «C:\Users\yveso\Downloads\multi-downloader-nx-2.0.14-win64\videos\[Funimation] D.Gray-man - S01E01 [432p].audio.jpn.ts»...
[INFO] 10 of 689 parts downloaded [1%] (7m24s | 0.099Mb/s)
[INFO] 20 of 689 parts downloaded [3%] (5m47s | 0.12Mb/s)
[INFO] 30 of 689 parts downloaded [4%] (4m52s | 0.15Mb/s)
[INFO] 40 of 689 parts downloaded [6%] (5m08s | 0.14Mb/s)
[INFO] 50 of 689 parts downloaded [7%] (5m00s | 0.14Mb/s)
[INFO] 60 of 689 parts downloaded [9%] (5m13s | 0.13Mb/s)
[INFO] 70 of 689 parts downloaded [10%] (4m57s | 0.14Mb/s)
[INFO] 80 of 689 parts downloaded [12%] (4m43s | 0.14Mb/s)
[INFO] 90 of 689 parts downloaded [13%] (4m27s | 0.15Mb/s)
[INFO] 100 of 689 parts downloaded [15%] (4m22s | 0.15Mb/s)
[INFO] 110 of 689 parts downloaded [16%] (4m12s | 0.15Mb/s)
[INFO] 120 of 689 parts downloaded [17%] (3m59s | 0.15Mb/s)
[INFO] 130 of 689 parts downloaded [19%] (3m49s | 0.16Mb/s)
[INFO] 140 of 689 parts downloaded [20%] (3m47s | 0.16Mb/s)
[INFO] 150 of 689 parts downloaded [22%] (3m53s | 0.15Mb/s)
[INFO] 160 of 689 parts downloaded [23%] (3m46s | 0.15Mb/s)
[INFO] 170 of 689 parts downloaded [25%] (3m38s | 0.15Mb/s)
[INFO] 180 of 689 parts downloaded [26%] (3m35s | 0.15Mb/s)
[INFO] 190 of 689 parts downloaded [28%] (3m31s | 0.15Mb/s)
[INFO] 200 of 689 parts downloaded [29%] (3m30s | 0.15Mb/s)
[INFO] 210 of 689 parts downloaded [30%] (3m32s | 0.15Mb/s)
[INFO] 220 of 689 parts downloaded [32%] (3m26s | 0.15Mb/s)
[INFO] 230 of 689 parts downloaded [33%] (3m18s | 0.15Mb/s)
[INFO] 240 of 689 parts downloaded [35%] (3m12s | 0.15Mb/s)
[INFO] 250 of 689 parts downloaded [36%] (3m06s | 0.15Mb/s)
[INFO] 260 of 689 parts downloaded [38%] (2m59s | 0.15Mb/s)
[INFO] 270 of 689 parts downloaded [39%] (2m57s | 0.15Mb/s)
[INFO] 280 of 689 parts downloaded [41%] (2m51s | 0.15Mb/s)
[INFO] 290 of 689 parts downloaded [42%] (2m49s | 0.15Mb/s)
[INFO] 300 of 689 parts downloaded [44%] (2m44s | 0.15Mb/s)
[INFO] 310 of 689 parts downloaded [45%] (2m39s | 0.15Mb/s)
[INFO] 320 of 689 parts downloaded [46%] (2m34s | 0.16Mb/s)
[INFO] 330 of 689 parts downloaded [48%] (2m28s | 0.16Mb/s)
[INFO] 340 of 689 parts downloaded [49%] (2m23s | 0.16Mb/s)
[INFO] 350 of 689 parts downloaded [51%] (2m18s | 0.16Mb/s)
[INFO] 360 of 689 parts downloaded [52%] (2m12s | 0.16Mb/s)
[INFO] 370 of 689 parts downloaded [54%] (2m08s | 0.16Mb/s)
[INFO] 380 of 689 parts downloaded [55%] (2m03s | 0.16Mb/s)
[INFO] 390 of 689 parts downloaded [57%] (1m58s | 0.16Mb/s)
[INFO] 400 of 689 parts downloaded [58%] (1m57s | 0.16Mb/s)
[INFO] 410 of 689 parts downloaded [60%] (1m52s | 0.16Mb/s)
[INFO] 420 of 689 parts downloaded [61%] (1m47s | 0.16Mb/s)
[INFO] 430 of 689 parts downloaded [62%] (1m46s | 0.16Mb/s)
[INFO] 440 of 689 parts downloaded [64%] (1m41s | 0.16Mb/s)
[INFO] 450 of 689 parts downloaded [65%] (1m36s | 0.16Mb/s)
[INFO] 460 of 689 parts downloaded [67%] (1m32s | 0.16Mb/s)
[INFO] 470 of 689 parts downloaded [68%] (1m28s | 0.16Mb/s)
[INFO] 480 of 689 parts downloaded [70%] (1m23s | 0.16Mb/s)
[INFO] 490 of 689 parts downloaded [71%] (1m19s | 0.16Mb/s)
[INFO] 500 of 689 parts downloaded [73%] (1m15s | 0.16Mb/s)
[INFO] 510 of 689 parts downloaded [74%] (1m11s | 0.16Mb/s)
[INFO] 520 of 689 parts downloaded [75%] (1m08s | 0.16Mb/s)
[INFO] 530 of 689 parts downloaded [77%] (1m03s | 0.16Mb/s)
[INFO] 540 of 689 parts downloaded [78%] (1m00s | 0.16Mb/s)
[INFO] 550 of 689 parts downloaded [80%] (56s | 0.16Mb/s)
[INFO] 560 of 689 parts downloaded [81%] (52s | 0.16Mb/s)
[INFO] 570 of 689 parts downloaded [83%] (49s | 0.16Mb/s)
[INFO] 580 of 689 parts downloaded [84%] (45s | 0.16Mb/s)
[INFO] 590 of 689 parts downloaded [86%] (41s | 0.16Mb/s)
[INFO] 600 of 689 parts downloaded [87%] (37s | 0.16Mb/s)
[INFO] 610 of 689 parts downloaded [89%] (32s | 0.16Mb/s)
[INFO] 620 of 689 parts downloaded [90%] (28s | 0.16Mb/s)
[INFO] 630 of 689 parts downloaded [91%] (24s | 0.16Mb/s)
[INFO] 640 of 689 parts downloaded [93%] (20s | 0.16Mb/s)
[INFO] 650 of 689 parts downloaded [94%] (16s | 0.16Mb/s)
[INFO] 660 of 689 parts downloaded [96%] (12s | 0.16Mb/s)
[INFO] 670 of 689 parts downloaded [97%] (8s | 0.16Mb/s)
[INFO] 680 of 689 parts downloaded [99%] (4s | 0.16Mb/s)
[INFO] 689 of 689 parts downloaded [100%] (0s | 0.16Mb/s)
[WARN] FFmpeg not found, skip muxing...

[INFO] Done!

### Additional Information

This issue is easily resolved by configuring bin-path.yml from `ffmpeg: "./bin/ffmpeg/ffmpeg.exe"` to `FFmpeg: "./bin/ffmpeg/ffmpeg.exe"`.

A similar issue also shows up with MKVMerge that is likewise easily resolved by configuring bin-path.yml from `mkvmerge: "./bin/mkvtoolnix/mkvmerge.exe"` to `MKVMerge: "./bin/mkvtoolnix/mkvmerge.exe"`.

**Comment by izu-co** [comment] 2022-01-02 21:36
Just build the tool, so I can use the exe, and it worked just fine for me with these bins: 
```yaml
ffmpeg: "ffmpeg.exe"
mkvmerge: "mkvmerge.exe"
```

**Comment by BuckMisterFullerene** [comment] 2022-01-03 02:24
How do I do that (build the tool)? I know nothing about programming, so I apologize in advance.

**Comment by izu-co** [comment] 2022-01-03 13:18
Download the code from GitHub then first run `npm i` then `npm run build-win64`
The lib folder contains a _build folder where you can find the exe

**Comment by izu-co** [comment] 2022-01-03 15:18
I also checked the code and I have no idea why it should not work with `ffmpeg`. Can you zip the folder (make sure to delete the tokens beforehand) and upload it here, so I can take a look?

**Comment by BuckMisterFullerene** [comment] 2022-01-03 16:43
Hi. I tried to run `npm run build-win64` after `npm i`, but this showed up:

```yaml
> multi-downloader-nx@2.0.14 prebuild-win64
> npm run tsc


> multi-downloader-nx@2.0.14 tsc
> ts-node tsc.ts


> multi-downloader-nx@2.0.14 build-win64
> cd lib && node modules/build win64

[Build] Build configuration: multi-downloader-nx-2.0.14-win64
> pkg@5.5.1
'7z' is not recognized as an internal or external command,
operable program or batch file.
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: 7z a -t7z "./_builds/multi-downloader-nx-2.0.14-win64.7z" "./_builds/multi-downloader-nx-2.0.14-win64"
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at C:\Users\yveso\OneDrive\Desktop\multi-downloader-nx-2.0.14\lib\modules\build.js:109:50
    at step (C:\Users\yveso\OneDrive\Desktop\multi-downloader-nx-2.0.14\lib\modules\build.js:33:23)
    at Object.next (C:\Users\yveso\OneDrive\Desktop\multi-downloader-nx-2.0.14\lib\modules\build.js:14:53)
    at fulfilled (C:\Users\yveso\OneDrive\Desktop\multi-downloader-nx-2.0.14\lib\modules\build.js:5:58) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2196,
  stdout: null,
  stderr: null
}
```

Also, here's the folder:
[multi-downloader-nx-2.0.14-win64.zip](https://github.com/anidl/multi-downloader-nx/files/7803020/multi-downloader-nx-2.0.14-win64.zip)

**Comment by izu-co** [comment] 2022-01-03 18:40
The error happens because you don't have 7zip, but that is not an issue. The folder should be there anyway.

**Comment by izu-co** [comment] 2022-01-03 18:48
Just tested it again with the zip you provided, and it worked. Since I can't reproduce it, and you found a fix for yourself, I am going to close this issue.

But, by any means, if you find an issue like this again, feel free to report it at any time.

**Closed by izu-co** 2022-01-03 18:48 UTC
Labels: bug

**Comment by BuckMisterFullerene** [comment] 2022-01-04 06:27
Yeah, I used the exe in the _build folder, but the problem still persisted. I did find out though that I don't I have to change bin-path.yml from
```yaml
ffmpeg: "ffmpeg.exe"
mkvmerge: "mkvmerge.exe"
```
to
```yaml
FFmpeg: "./bin/ffmpeg/ffmpeg.exe"
MKVMerge: "mkvmerge: "./bin/mkvtoolnix/mkvmerge.exe"
```
just
```yaml
FFmpeg: "ffmpeg.exe"
MKVMerge: "mkvmerge.exe"
```
> But, by any means, if you find an issue like this again, feel free to report it at any time.
I will! 
> PS: Welcome to GitHub 🎉
Thanks!
