### ISSUE TITLE
[BUG]: Multi-dub issues

### ISSUE THREAD

**Issue by slimshot** [anidl/multi-downloader-nx#502] opened 2023-07-13 19:44 UTC
### Program version

4.1.0

### Operating System

Windows

### Type

CLI

### Service

Crunchyroll

### Command used

.\aniDL.exe --service crunchy --srz GQWH0M1GG -s GRGGCVQGV -e 1 --dlVideoOnce --dubLang jpn spa-419  fra eng --dlsubs es-419 fr en --defaultSub spa-419

### Show ID

GQWH0M1GG

### Episode

1

### Console Output

```Shell
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Cannot read properties of undefined (reading 'cr_locale')
    at C:\snapshot\multi-downloader-nx\lib\crunchy.js
    at Array.find (<anonymous>)
    at _loop_6 (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at C:\snapshot\multi-downloader-nx\lib\crunchy.js
    at Array.forEach (<anonymous>)
    at C:\snapshot\multi-downloader-nx\lib\crunchy.js
    at step (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at Object.next (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at step (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
    at Object.next (C:\snapshot\multi-downloader-nx\lib\crunchy.js)
```

**Comment by AnimeDL** [comment] 2023-07-13 19:49
This is caused by a language that episode is in not being available, it is fixed in the upcoming 4.2.0 version

**Closed** 2023-07-13 22:27 UTC
Labels: bug
