### ISSUE TITLE
Different Dubs get treated as the same

### ISSUE THREAD

**Issue by OryWareKyrie** [anidl/multi-downloader-nx#232] opened 2022-01-24 13:39 UTC
oops manin are you ok? I don't know if I already reported this to you in your repo but then. some episodes of titles on funimation the tool can't pull the subtitles even though it's available. for example, the spanish and portuguese subtitles of episode 12 of akudama drive
```
C:\Ory\multi-downloader-nx-18.01.22\lib>node index.js --service funi -s 1159388 -e 12 -q 7 --dubLang jpn por

=== Multi Downloader NX 2.0.18 ===

[#1159388] Akudama Drive (2020)
[0001] Akudama Drive - #01 SE7EN (00:23:40) [HD1080, Portuguese, Japanese, Spanish]
[0002] Akudama Drive - #02 RESERVOIR DOGS (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0003] Akudama Drive - #03 MISSION: IMPOSSIBLE (00:23:39) [HD1080, Portuguese, Japanese, Spanish]
[0004] Akudama Drive - #04 SPEED (00:23:40) [HD1080, Portuguese, Japanese, Spanish]
[0005] Akudama Drive - #05 DEAD MAN WALKING (00:23:40) [HD1080, Portuguese, Japanese, Spanish]
[0006] Akudama Drive - #06 BROTHER (00:23:40) [HD1080, Portuguese, Japanese, Spanish]
[0007] Akudama Drive - #07 The City of Lost Children (00:23:39) [SD540, Japanese, Spanish, Portuguese]
[0008] Akudama Drive - #08 BLACK RAIN (00:23:40) [HD1080, Spanish, Japanese, Portuguese]
[0009] Akudama Drive - #09 THE SHINING (00:23:40) [HD1080, Spanish, Japanese, Portuguese]
[0010] Akudama Drive - #10 BABEL (00:23:40) [HD1080, Spanish, Japanese, Portuguese]
[0011] Akudama Drive - #11 WAR GAMES (00:23:40) [HD1080, Spanish, Japanese, Portuguese]
[0012] Akudama Drive - #12 AKUDAMA DRIVE (00:23:40) [HD1080, Spanish, Japanese, Portuguese] (selected)

[INFO] Selected Episodes: 0012

[INFO] Akudama Drive - S1E12 - AKUDAMA DRIVE
[INFO] Available streams (Non-Encrypted):
[#1176388] Japanese [Simulcast] (selected) (using 'English' for subtitles)
[#3950972] Portuguese (Brazil) [Simulcast] (selected)
[#3960293] Spanish (Latin Am) [Simulcast]
```

![image](https://user-images.githubusercontent.com/31232184/150788425-b94be4ca-27e8-4918-9e13-de83f8901d33.png)
is there a way to fix it? is also setting the wrong tag at the time of the mux, from "por" to "spa". 
```
General
Unique ID                   : 13971173823890367773616739708859979304 (0xA82C00D468275DD7DB7C49CCBCE1628)
Complete name               : C:\Ory\multi-downloader-nx-18.01.22\lib\videos\Akudama Drive (2020) 720p FUNI WEB-DL AVC AAC2.0-Ory\Akudama Drive E12 720p Funimation WEB-DL AVC AAC2.0-Ory.mkv
Format                      : Matroska
Format version              : Version 4
File size                   : 702 MiB
Duration                    : 23 min 47 s
Overall bit rate            : 4 125 kb/s
Encoded date                : UTC 2022-01-21 22:58:29
Writing application         : mkvmerge v62.0.0 ('Apollo') 64-bit
Writing library             : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4
Format settings             : CABAC / 3 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 3 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 23 min 47 s
Bit rate                    : 3 610 kb/s
Width                       : 1 280 pixels
Height                      : 720 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.163
Stream size                 : 614 MiB (88%)
Title                       : Japanese [Uncut]
Language                    : Japanese
Default                     : Yes
Forced                      : No
Color range                 : Limited
Matrix coefficients         : BT.709

Audio #1
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : A_AAC-2
Duration                    : 23 min 47 s
Bit rate                    : 256 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 43.6 MiB (6%)
Title                       : Japanese
Language                    : Japanese
Default                     : Yes
Forced                      : No

Audio #2
ID                          : 3
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : A_AAC-2
Duration                    : 23 min 47 s
Bit rate                    : 256 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 43.6 MiB (6%)
Title                       : Spanish
Language                    : Spanish
Default                     : Yes
Forced                      : No

Text
ID                          : 4
Format                      : ASS
Codec ID                    : S_TEXT/ASS
Codec ID/Info               : Advanced Sub Station Alpha
Duration                    : 21 min 31 s
Bit rate                    : 77 b/s
Count of elements           : 230
Compression mode            : Lossless
Stream size                 : 12.1 KiB (0%)
Title                       : English
Language                    : English
Default                     : Yes
Forced                      : No
``` 
Could you add an option to choose the update check period? type every 7 days or so. currently it is every 24 hours right?

**Comment by OryWareKyrie** [comment] 2022-01-24 17:10
> According to your command you're not downloading subtitles. Use --dlsubs to download subtitles.

but I didn't need to use it because it downloaded the subtitles, as you can see in mediainfo. only ep 12 that didn't download

**Comment by izu-co** [comment] 2022-01-24 17:36
> According to your command you're not downloading subtitles. Use --dlsubs to download subtitles.

[Please see the docs](https://github.com/anidl/multi-downloader-nx/blob/master/docs/DOCUMENTATION.md#--dlsubs) where you can find that `all` is the default option for downloading subtitles. So there is no need to specify them.

> Could you add an option to choose the update check period? type every 7 days or so. currently it is every 24 hours right?

I could, but is there a need for that? `I` think that the 24 hours (you are right with the time) is quite enough. Or is there a reason why you would like to change that?

**Comment by OryWareKyrie** [comment] 2022-01-24 17:51
> I could, but is there a need for that? `I` think that the 24 hours (you are right with the time) is quite enough. Or is there a reason why you would like to change that?

there is no specific reason it would be more for customization

**Comment by izu-co** [comment] 2022-01-25 16:56
If I have the time to, I will implement it. As far as your other issue is concerned, I would like to pause it until the GUI has finished. It may take a while, but I don't wish to work on multiple fronts at once.

**Comment by izu-co** [comment] 2022-02-16 11:44
About the subtitles: They are not returned by the API (I think that's why they have no names) and I have no idea where they are coming from...

**Comment by izu-co** [comment] 2022-02-16 11:59
I found a few URLs that might be new. I have to look at them in detail later, but they seam to carry the subtitle information we need.

**Comment by OryWareKyrie** [comment] 2022-02-26 23:37
oops all right?! I tested it here and it's getting the "hidden" subtitles, thanks. but it is still setting audio "por" to "spa". if I try to download both, "por" and "spa" returns this.

```[INFO] Output filename: [Funimation] My Dress-Up Darling - S01E05 [720p].ts
[Q] File «C:\Users\Ory\Downloads\Compressed\multi-downloader\lib\videos\[Funimation] My Dress-Up Darling - S01E05 [720p].audio.spa.ts» already exists! Rewrite? ([y]es/[N]o/[c]ontinue):
```
but thanks once again for your time working on this.

**Comment by izu-co** [comment] 2022-02-27 09:22
I will take a look at it

**Comment by izu-co** [comment] 2022-03-03 20:16
The newest commit should fix said issue. Funi seemed to have renamed `Latin Am` to `LAS`

**Comment by OryWareKyrie** [comment] 2022-03-04 01:13
A thousand apologies @izu-co for giving so much work. but the same thing happens with the subtitles "por" and "eng". in the image the three options are hidden but the tool only downloaded the "spa". I believe there is a link for them too. can you have a look?
![image](https://user-images.githubusercontent.com/31232184/156679438-494a837e-fad0-4d5f-80d4-e29eb1a59998.png)
you're ![image](https://c.tenor.com/nKeXukcCQ3UAAAAM/10-10points.gif)

**Comment by izu-co** [comment] 2022-03-17 21:45
Just a quick question: Do you know if the issue is still there?

**Comment by OryWareKyrie** [comment] 2022-03-17 22:38
> Just a quick question: Do you know if the issue is still there?

Yes. 
```=== Multi Downloader NX 3.0.4 ===

[#1320566] BACK ARROW (2021)
[0001] BACK ARROW - #01 Do Guys From the Sky Have Undies? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0002] BACK ARROW - #02 Is Having Dreams a Burden? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0003] BACK ARROW - #03 Does a Huge Ship Bring Hope? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0004] BACK ARROW - #04 Does Genius Come When Least Expected? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0005] BACK ARROW - #05 Is Today Yesterday's Tomorrow? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0006] BACK ARROW - #06 Are Pretty Boy Farms a Thing? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0007] BACK ARROW - #07 Is the Wall Really That Solid? (00:23:40) [HD1080, Japanese, Portuguese, Spanish] (selected)
[0008] BACK ARROW - #08 What is the Bloodstained Knight Hiding? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0009] BACK ARROW - #09 Why Do Lips that Profess Love Hide Fangs? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0010] BACK ARROW - #10 Can Have-Nots Have Backbone? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0011] BACK ARROW - #11 Is This a Head-to-Head Fight? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0012] BACK ARROW - #12 Is Too Much Pride A Problem? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0013] BACK ARROW - #13 Do the Heavens Cry When the Princess Rises? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0014] BACK ARROW - #14 Is There Love on the Battlefield? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0015] BACK ARROW - #15 What Will the Riots Produce? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0016] BACK ARROW - #16 When People Want Peace, What Does God Want? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0017] BACK ARROW - #17 Is This How They Rise Up? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0018] BACK ARROW - #18 Is This the World's Truth? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0019] BACK ARROW - #19 Can You Sort This Out? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0020] BACK ARROW - #20 Does People's Anger Reach God? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0021] BACK ARROW - #21 Who Will Stop Me? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0022] BACK ARROW - #22 But What Do I Live For? (00:23:40) [HD1080, Japanese, Portuguese, Spanish]
[0023] BACK ARROW - #23 Does Destruction Rain From the Heavens? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]
[0024] BACK ARROW - #24 Do We Head for the Stars? (00:23:40) [HD1080, Japanese, Spanish, Portuguese]

[INFO] Selected Episodes: 0007

[INFO] BACK ARROW - S1E7 - Is the Wall Really That Solid?
[INFO] Available streams (Non-Encrypted):
[#1320702] Japanese [Simulcast] (selected) (using 'Spanish' for subtitles)
[#4039855] Portuguese (Brazil) [Simulcast] (selected) (using 'Spanish' for subtitles)
[#4039856] Spanish (Latin Am) [Simulcast]```

**Comment by izu-co** [comment] 2022-03-20 09:43
Should be fixed again with the newest commit

**Closed** 2022-03-20 09:43 UTC
Labels: bug

**Comment by OryWareKyrie** [comment] 2022-03-21 09:51
> Should be fixed again with the newest commit

thank you very much manin. I found another bug lol :smiley_cat:
