### ISSUE TITLE
Funimation not finding movie BUG

### ISSUE THREAD

**Issue by kn285** [anidl/multi-downloader-nx#290] opened 2022-03-21 15:05 UTC
### Program version

3.0.3

### Operating System

MacOS

### Type

Cli

### Service

Funimation

### Command used

aniDL --service funi -s 183044

### Show ID

183044

### Episode

M001

### Console Output

=== Multi Downloader NX 3.0.3 ===

[#183044] Dragon Ball Super (2015)
[0001] Dragon Ball Super - #01 The Peace Reward - Who Will Get the 100 Million Zeni? (23:26) [HD1080, Japanese, English]
[0002] Dragon Ball Super - #02 To the Promised Resort! Vegeta Goes on a Family Trip?! (23:26) [HD1080, English, Japanese]
[0003] Dragon Ball Super - #03 Where's the Rest of the Dream?! In Search of the Super Saiyan God! (23:26) [HD1080, English, Japanese]
[0004] Dragon Ball Super - #04 Aim for the Dragon Balls! Pilaf Gang in Action! (23:26) [HD1080, English, Japanese]
[0005] Dragon Ball Super - #05 The Ultimate Fight on King Kai's Planet! Goku Vs the God of Destruction Beerus (23:26) [HD1080, English, Japanese]
[0006] Dragon Ball Super - #06 Don't Anger the God of Destruction! Excitement at the Birthday Party (23:26) [HD1080, English, Japanese]
[0007] Dragon Ball Super - #07 How Dare You Hurt My Bulma! Vegeta's Sudden, Angry Shift?! (23:26) [HD1080, Japanese, English]
[0008] Dragon Ball Super - #08 Goku Arrives! A Last Chance from Beerus Sama?! (23:26) [HD1080, English, Japanese]
[0009] Dragon Ball Super - #09 Sorry for the Wait, Beerus Sama. The Super Saiyan God Is Finally Born! (23:26) [HD1080, English, Japanese]
[0010] Dragon Ball Super - #10 Unleash It, Goku! The Power of the Super Saiyan God!! (23:26) [HD1080, English, Japanese]
[0011] Dragon Ball Super - #11 Let’s Keep Going, Lord Beerus! The Battle of Gods! (23:26) [HD1080, Japanese, English]
[0012] Dragon Ball Super - #12 The Universe Crumbles?! Clash! God of Destruction Vs. Super Saiyan God (23:26) [HD1080, English, Japanese]
[0013] Dragon Ball Super - #13 Goku, Surpass the Super Saiyan God! (23:26) [HD1080, Japanese, English]
[0014] Dragon Ball Super - #14 This Is Every Ounce of Power I Have! The Battle of Gods' Conclusion! (23:26) [HD1080, English, Japanese]
[0015] Dragon Ball Super - #15 Make a Miracle, Satan the Hero! A Challenge from Outer Space (23:26) [HD1080, Japanese, English]
[0016] Dragon Ball Super - #16 Vegeta Becomes an Apprentice?! Winning Whis Over! (23:26) [HD1080, English, Japanese]
[0017] Dragon Ball Super - #17 Pan Is Born! And Goku Goes on a Training Trip?! (23:26) [HD1080, Japanese, English]
[0018] Dragon Ball Super - #18 I'm Here, Too! Training Begins on Beerus' Planet! (23:26) [HD1080, English, Japanese]
[0019] Dragon Ball Super - #19 Despair Rises! The Emperor of Evil, Frieza, Resurrected! (23:26) [HD1080, Japanese, English]
[0020] Dragon Ball Super - #20 Jaco's Warning! Frieza and His 1000 Troops Approach (23:26) [HD1080, English, Japanese]
[0021] Dragon Ball Super - #21 The Start of Revenge! the Malice of Frieza Army Strikes Gohan! (23:26) [HD1080, English, Japanese]
[0022] Dragon Ball Super - #22 Change! an Unexpected Return! His Name Is Ginyu!! (23:26) [HD1080, English, Japanese]
[0023] Dragon Ball Super - #23 The Earth! Gohan! Absolute Peril! Hurry and Get Here, Son Goku!! (23:26) [HD1080, English, Japanese]
[0024] Dragon Ball Super - #24 Clash! Frieza Vs Son Goku - This Is The Result of My Training! (23:26) [HD1080, English, Japanese]
[0025] Dragon Ball Super - #25 An All-Out Battle! The Revenge of Golden Frieza (23:26) [HD1080, English, Japanese]
[0026] Dragon Ball Super - #26 A Glint of Hope Shines Through in a Crisis! Time to Fight Back, Son Goku! (23:26) [HD1080, English, Japanese]
[0027] Dragon Ball Super - #27 The Earth Explodes?! The Deciding Kamehameha (23:26) [HD1080, English, Japanese]
[0028] Dragon Ball Super - #28 The God of Destruction from Universe 6 - His Name Is Champa (23:26) [HD1080, English, Japanese]
[0029] Dragon Ball Super - #29 The Martial Arts Match Has Been Decided! The Team Captain Is Stronger Than Goku (23:26) [HD1080, Japanese, English]
[0030] Dragon Ball Super - #30 A Review Before the 'Martial Arts Match' - Who Are the Last Two Members?! (23:26) [HD1080, Japanese, English]
[0031] Dragon Ball Super - #31 Off to Zuno Sama's! Find Out Where Super Dragon Balls Are! (23:26) [HD1080, Japanese, English]
[0032] Dragon Ball Super - #32 The Match Begins! Let's All Go to the Nameless Planet! (23:26) [HD1080, Japanese, English]
[0033] Dragon Ball Super - #33 Behold, Universe 6! This Is the Super Saiyan? Son Goku! (23:26) [HD1080, English, Japanese]
[0034] Dragon Ball Super - #34 Piccolo Vs. Frost - Put It All on the Special Beam Cannon! (23:26) [HD1080, English, Japanese]
[0035] Dragon Ball Super - #35 Turn Rage into Strength! Vegeta's Full-On Battle (23:26) [HD1080, Japanese, English]
[0036] Dragon Ball Super - #36 An Unexpected Desperate Battle! Vegeta's Furious Explosion! (23:26) [HD1080, English, Japanese]
[0037] Dragon Ball Super - #37 Don't Forget Your Saiyan Pride! Vegeta Vs the Saiyan of Universe 6 (23:26) [HD1080, English, Japanese]
[0038] Dragon Ball Super - #38 The Ultimate Warrior of Universe 6! Assassin Hit Appears!! (23:26) [HD1080, Japanese, English]
[0039] Dragon Ball Super - #39 The Advanced 'Time-Skip' Fights Back?! Will It Come Forth? Goku's New Technique! (23:26) [HD1080, English, Japanese]
[0040] Dragon Ball Super - #40 At Last, It Comes to an End! Is the Winner Beerus? Or is it Champa? (23:26) [HD1080, Japanese, English]
[0041] Dragon Ball Super - #41 Come, God of Dragons - And Pretty Please Grant My Wish! (23:26) [HD1080, Japanese, English]
[0042] Dragon Ball Super - #42 Trouble at the Victory Celebration! Showdown at Last?! Monaka vs. Son Goku (23:26) [HD1080, English, Japanese]
[0043] Dragon Ball Super - #43 Goku's "Ki" is Out of Control?! Looking After Pan is A Lot of Trouble (23:26) [HD1080, English, Japanese]
[0044] Dragon Ball Super - #44 Seal of Planet Potofu - Secret of the Superhuman Water is Unleashed (23:26) [HD1080, Japanese, English]
[0045] Dragon Ball Super - #45 Vegeta Disappears?! The Threat of Duplicated Vegeta! (23:26) [HD1080, Japanese, English]
[0046] Dragon Ball Super - #46 Goku vs. Duplicated Vegeta! Who's Gonna Win?! (23:26) [HD1080, Japanese, English]
[0047] Dragon Ball Super - #47 An SOS from the Future! A Dark New Enemy Emerges!! (23:26) [HD1080, English, Japanese]
[0048] Dragon Ball Super - #48 Hope!! Once More Awaken in the Present, Trunks (23:26) [HD1080, Japanese, English]
[0049] Dragon Ball Super - #49 A Message from the Future - Goku Black Strikes! (23:26) [HD1080, Japanese, English]
[0050] Dragon Ball Super - #50 Goku Vs Black! The Closed Path to the Future (23:26) [HD1080, Japanese, English]
[0051] Dragon Ball Super - #51 Feelings That Travel Beyond Time - Trunks and Mai (23:26) [HD1080, English, Japanese]
[0052] Dragon Ball Super - #52 Teacher and Student Reunited - Son Gohan and "Future" Trunks (23:26) [HD1080, Japanese, English]
[0053] Dragon Ball Super - #53 Uncover Black's Identity! To the Sacred World of the Kais! (23:26) [HD1080, Japanese, English]
[0054] Dragon Ball Super - #54 The One Who Inherits the Saiyan Blood - Trunk's Resolve (23:26) [HD1080, Japanese, English]
[0055] Dragon Ball Super - #55 I Want to See Son Goku - Zen‐Oh Sama's Summoning! (23:26) [HD1080, Japanese, English]
[0056] Dragon Ball Super - #56 Rematch With Goku Black! Super Saiyan Rosé Appears (23:26) [HD1080, Japanese, English]
[0057] Dragon Ball Super - #57 The God With the Immortal Body - Zamasu Descends (23:26) [HD1080, Japanese, English]
[0058] Dragon Ball Super - #58 Zamasu and Black - The Mystery of the Two Deepens (23:26) [HD1080, English, Japanese]
[0059] Dragon Ball Super - #59 Protect Supreme Kai Gowasu - Destroy Zamasu! (23:26) [HD1080, Japanese, English]
[0060] Dragon Ball Super - #60 Back to the Future - Goku Black's Identity Is Revealed!! (23:26) [HD1080, Japanese, English]
[0061] Dragon Ball Super - #61 Zamasu's Ambition - The Awful "Zero Mortal Plan" Is Revealed (23:26) [HD1080, Japanese, English]
[0062] Dragon Ball Super - #62 I'll Protect the World! Trunks' Furious Super Power Explodes!! (23:26) [HD1080, Japanese, English]
[0063] Dragon Ball Super - #63 Don't Disrespect Saiyan Cells! Vegeta's Heroic Battle Begins!! (23:26) [HD1080, Japanese, English]
[0064] Dragon Ball Super - #64 Revere Him! Praise Him! Fusion Zamasu's Explosive Birth!! (23:26) [HD1080, Japanese, English]
[0065] Dragon Ball Super - #65 Is This the Final Judgement?! The Ultimate Power of the Absolute God (23:26) [HD1080, Japanese, English]
[0066] Dragon Ball Super - #66 The Climactic Battle! The Miraculous Power of a Relentless Warrior! (23:26) [HD1080, Japanese, English]
[0067] Dragon Ball Super - #67 With New Hope!! In Our Hearts- Farewell, Trunks (23:26) [HD1080, Japanese, English]
[0068] Dragon Ball Super - #68 Come Forth, Shenron! Whose Wish Will be Granted?! (23:26) [HD1080, Japanese, English]
[0069] Dragon Ball Super - #69 Goku Vs Arale! A Ridiculous Battle Will End The Earth?! (23:26) [HD1080, Japanese, English]
[0070] Dragon Ball Super - #70 Champa's Challenge! This Time We Fight With Baseball! (23:26) [HD1080, Japanese, English]
[0071] Dragon Ball Super - #71 The Death of Goku! The Guaranteed Assassination Mission (23:26) [HD1080, Japanese, English]
[0072] Dragon Ball Super - #72 Will There Be A Counterattack?! The Invisible Killing Strike!! (23:26) [HD1080, Japanese, English]
[0073] Dragon Ball Super - #73 Gohan's Misfortune! An Unexpected Great Saiyaman Movie?! (23:26) [HD1080, Japanese, English]
[0074] Dragon Ball Super - #74 For the Ones He Loves! The Unbeatable Great Saiyaman!! (23:26) [HD1080, Japanese, English]
[0075] Dragon Ball Super - #75 Goku and Krillin Back to the Old Training Grounds (23:26) [HD1080, Japanese, English]
[0076] Dragon Ball Super - #76 Defeat These Terrifying Enemies! Krillin's Fighting Spirit Returns! (23:26) [HD1080, Japanese, English]
[0077] Dragon Ball Super - #77 Let's Do It, Zen-Oh Sama! The All-Universe Martial Arts Tournament!! (23:26) [HD1080, Japanese]
[0078] Dragon Ball Super - #78 The Gods of Every Universe In Shock?! Losers Erased In The Tournament Of Power (23:26) [HD1080, Japanese, English]
[0079] Dragon Ball Super - #79 Universe 9's Basil The Kicker VS Universe 7's Majin Buu!! (23:26) [HD1080, Japanese, English]
[0080] Dragon Ball Super - #80 Awaken Your Sleeping Battle Spirit! Son Gohan's Fight!! (23:26) [HD1080, Japanese, English]
[0081] Dragon Ball Super - #81 Bergamo The Crusher VS Son Goku! Which One Wields The Limtless Power?! (23:26) [HD1080, Japanese]
[0082] Dragon Ball Super - #82 Never Forgive Son Goku! Toppo The Warrior Of Justice Intrudes!! (23:26) [HD1080, Japanese, English]
[0083] Dragon Ball Super - #83 Form the Universe 7 Representing Team! Who are the Strongest Ten?! (23:26) [HD1080, Japanese, English]
[0084] Dragon Ball Super - #84 Son Goku The Recruiter Invites Krillin And No. 18 (23:26) [HD1080, Japanese, English]
[0085] Dragon Ball Super - #85 The Universes Begin To Make Their Moves Their Individual Motives (23:26) [HD1080, Japanese, English]
[0086] Dragon Ball Super - #86 Fists Cross For The First Time! Android #17 Vs Son Goku!! (23:26) [HD1080, Japanese, English]
[0087] Dragon Ball Super - #87 Hunt The Poachers! Goku And No. 17's United Front!! (23:26) [HD1080, Japanese, English]
[0088] Dragon Ball Super - #88 Gohan And Piccolo Teacher And Pupil Clash In Max Training! (23:26) [HD1080, Japanese, English]
[0089] Dragon Ball Super - #89 An Unkown Beauty Appears! The Tenshin-style Dojo's Mystery?! (23:26) [HD1080, Japanese, English]
[0090] Dragon Ball Super - #90 See The Wall That Must Be Passed! Goku Vs Gohan (23:26) [HD1080, Japanese, English]
[0091] Dragon Ball Super - #91 Which Universe Will Survive?! The Strongest Warriors Are Gathering!! (23:26) [HD1080, Japanese, English]
[0092] Dragon Ball Super - #92 Emergency Development! The Incomplete Ten Members!! (23:26) [HD1080, Japanese, English]
[0093] Dragon Ball Super - #93 You're The Tenth Warrior! Goku Goes To See Frieza!! (23:26) [HD1080, Japanese, English]
[0094] Dragon Ball Super - #94 The Emperor of Evil Returns! A Reception of Mysterious Assassins?! (23:26) [HD1080, Japanese, English]
[0095] Dragon Ball Super - #95 The Worst! The Most Evil! Frieza's Rampage!! (23:26) [HD1080, Japanese, English]
[0096] Dragon Ball Super - #96 The Time Is Here! To The World Of Void For The Fate Of The Universe!! (23:26) [HD1080, Japanese, English]
[0097] Dragon Ball Super - #97 Survive! The Tournament Of Power Begins At Last!! (23:26) [HD1080, Japanese, English]
[0098] Dragon Ball Super - #98 Oh, Uncertainty! A Universe Despairs!! (23:26) [HD1080, Japanese, English]
[0099] Dragon Ball Super - #99 Show Them! Krillin's True Power!! (23:26) [HD1080, Japanese, English]
[0100] Dragon Ball Super - #100 Out Of Control! The Savage Berserker Awakens!! (23:26) [HD1080, Japanese, English]
[0101] Dragon Ball Super - #101 The Impending Warriors of Justice! The Pride Troopers!! (23:26) [HD1080, Japanese, English]
[0102] Dragon Ball Super - #102 The Power of Love Explodes?! Universe 2's Little Witch Warriors!! (23:26) [HD1080, Japanese, English]
[0103] Dragon Ball Super - #103 Gohan, Show No Mercy! Showdown With Universe 10!! (23:26) [HD1080, Japanese, English]
[0104] Dragon Ball Super - #104 The Ultimate High Speed Battle Begins! Goku and Hit Join Forces!! (23:26) [HD1080, Japanese, English]
[0105] Dragon Ball Super - #105 A Desperate Battle! Master Roshi’s Sacrifice!! (23:03) [HD1080, Japanese, English]
[0106] Dragon Ball Super - #106 Find Them Out! Deathmatch with a Furtive Attacker!! (23:03) [HD1080, Japanese, English]
[0107] Dragon Ball Super - #107 Revenge "F!" A Cunning Trap Is Set?! (23:03) [HD1080, Japanese, English]
[0108] Dragon Ball Super - #108 Frieza and Frost! A Mutual Malevolence?! (23:03) [HD1080, Japanese, English]
[0109] Dragon Ball Super - #109 The Mightiest Enemy Zeroes In on Goku! Launch the Knockout Spirit Bomb Now! (22:48) [HD1080, Japanese, English]
[0110] Dragon Ball Super - #110 Goku Enkindled! The Awakened One's New Ultra Instinct!! (22:48) [HD1080, English, Japanese]
[0111] Dragon Ball Super - #111 An Extra-Dimensional Ultimate Battle! Hit vs. Jiren!! (22:48) [HD1080, Japanese, English]
[0112] Dragon Ball Super - #112 A Saiyan Oath! Vegeta’s Resolve!! (22:48) [HD1080, Japanese, English]
[0113] Dragon Ball Super - #113 With Great Joy! The Fighting Freak Saiyans' Battle Rejoined!! (22:48) [HD1080, Japanese, English]
[0114] Dragon Ball Super - #114 Bloodcurdling! The Explosive Birth of a New Super Warrior!! (22:48) [HD1080, Japanese, English]
[0115] Dragon Ball Super - #115 Goku vs. Kefla! Super Saiyan Blue Beaten?! (22:48) [HD1080, Japanese, English]
[0116] Dragon Ball Super - #116 Signs of a Turnabout! The Autonomous Ultra Instinct Erupts!! (22:48) [HD1080, Japanese, English]
[0117] Dragon Ball Super - #117 Showdown of Love! The Artificial Humans vs. the 2nd Universe!! (22:48) [HD1080, Japanese, English]
[0118] Dragon Ball Super - #118 Accelerating Tragedy – Vanishing Universes… (23:26) [HD1080, Japanese, English]
[0119] Dragon Ball Super - #119 Unavoidable?! The Ferocity of a Stealth Attack! (23:26) [HD1080, Japanese, English]
[0120] Dragon Ball Super - #120 A Perfect Survival Strategy! The 3rd Universe's Menacing Assassin!! (23:26) [HD1080, Japanese, English]
[0121] Dragon Ball Super - #121 All-Out War! The Ultimate Four-Fold Union vs. the 7th Universe's Total Offensive!! (23:26) [HD1080, Japanese, English]
[0122] Dragon Ball Super - #122 With His Pride on the Line! Vegeta's Challenge to Be the Strongest!! (23:26) [HD1080, Japanese, English]
[0123] Dragon Ball Super - #123 Body, Soul and Power Unleashed! Goku and Vegeta!! (23:26) [HD1080, Japanese, English]
[0124] Dragon Ball Super - #124 A Storm-and-Stress Assault! Gohan's Last Stand!! (23:26) [HD1080, Japanese, English]
[0125] Dragon Ball Super - #125 With Imposing Presence! God of Destruction Top Descends!! (23:26) [HD1080, Japanese, English]
[0126] Dragon Ball Super - #126 Surpass Even a God! Vegeta's Sacrifice Strike!! (23:26) [HD1080, Japanese, English]
[0127] Dragon Ball Super - #127 The Approaching Wall! A Hopeful Final Barrier!! (23:26) [HD1080, Japanese, English]
[0128] Dragon Ball Super - #128 To the Noble, Proud End! Vegeta Falls! (23:26) [HD1080, Japanese, English]
[0129] Dragon Ball Super - #129 A Transcendent Limit Break! Autonomous Ultra Instinct Mastered!! (23:26) [HD1080, Japanese, English]
[0130] Dragon Ball Super - #130 The Greatest Showdown of all Time! The Ultimate Survival Battle!! (23:26) [HD1080, Japanese, English]
[0131] Dragon Ball Super - #131 A Miraculous Conclusion! Farewell Goku! Until We Meet Again!! (23:26) [HD1080, Japanese, English]

### Additional Information

```Text
Funimation Doesn't recognize the Movie with Australian VPN. It finds other shows' movies but this specific show doesn't find it.
```

**Comment by izu-co** [comment] 2022-03-22 17:58
It seems like they are using a new API (maybe?). The reported item seems only visible to the CloudFront API, which we are actively trying to avoid in order to not get blocked.

Therefore, with my eyes on the merge of funi and crunchy I won't investigate any further. If someone has the time (I don't) to fix this, please feel free to open a PR.

**Comment by AnimeDL** [comment] 2023-07-14 00:40
I'm going to close this issue because I can't replicate it, or rather I don't even see the movie listed. If you have more information or the issue is still relevant, feel free to re-open

**Closed by AnimeDL** 2023-07-14 00:40 UTC
Labels: bug, help wanted
